# Generated by Django 3.2.3 on 2021-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark1', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=10)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
